
;;; Code:

(require 'layman-counsel)
(require 'layman-ivy)
(require 'layman-flycheck)
(require 'layman-amx)
(require 'layman-ace)
(require 'layman-mwim)
(require 'layman-hydra)
(require 'layman-undo)
(require 'layman-good-scroll)
(require 'layman-which-key)
(require 'layman-embark)
(require 'layman-avy)
;;(require 'layman-marginalia)
(require 'layman-rainbow-delimiters)
(require 'layman-company)
(require 'layman-yasnippet)
(require 'layman-lsp)
;;(require 'layman-projectile)
;;(require 'layman-shell)
;;(require 'layman-magit)
(require 'layman-cc)
;;(require 'layman-rust)
(require 'layman-python)
;;(require 'layman-treemacs)
(require 'layman-google-c-style)
(require 'layman-switch-window)
(require 'layman-protobuf)
(require 'layman-bazel)

(provide 'layman-extensions)
;;; layman-extensions.el ends here
